#
# DO NOT MODIFY!!!!
# This file is automatically generated by Racc 1.4.6
# from Racc grammer file "".
#

require 'racc/parser.rb'

  require "lexer"
  require "nodes"

class Parser < Racc::Parser

module_eval(<<'...end grammar.y/module_eval...', 'grammar.y', 159)
  def parse(code, show_tokens=false)
    @tokens = Lexer.new.run(code)
    p @tokens if show_tokens
    do_parse
  end
  
  def next_token
    @tokens.shift
  end
...end grammar.y/module_eval...
##### State transition tables begin ###

racc_action_table = [
    22,    23,     5,    15,    16,    17,    18,    19,    20,    24,
    73,    45,    21,    22,    23,     5,    15,    16,    17,    18,
    19,    20,    24,    70,    44,    21,    81,     6,    14,     5,
    22,    23,    48,    15,    16,    17,    18,    19,    20,    24,
     6,    14,    21,    22,    23,     5,    15,    16,    17,    18,
    19,    20,    24,    46,     6,    21,    22,    23,    14,    15,
    16,    17,    18,    19,    20,    24,    70,    27,    21,    69,
     6,    14,     5,    22,    23,     5,    15,    16,    17,    18,
    19,    20,    24,    27,    14,    21,    22,    23,     5,    15,
    16,    17,    18,    19,    20,    24,    80,     6,    21,    42,
     6,    14,    41,    22,    23,    68,    15,    16,    17,    18,
    19,    20,    24,     6,    14,    21,    22,    23,    83,    15,
    16,    17,    18,    19,    20,    24,    25,     5,    21,    22,
    23,    14,    15,    16,    17,    18,    19,    20,    24,    27,
   nil,    21,    22,    23,    14,    15,    16,    17,    18,    19,
    20,    24,     6,    66,    21,    79,   nil,    14,    78,    22,
    23,     5,    15,    16,    17,    18,    19,    20,    24,   nil,
    14,    21,    22,    23,     5,    15,    16,    17,    18,    19,
    20,    24,    77,   nil,    21,   nil,     6,    14,   nil,    22,
    23,   nil,    15,    16,    17,    18,    19,    20,    24,     6,
    14,    21,    22,    23,   nil,    15,    16,    17,    18,    19,
    20,    24,   nil,   nil,    21,    22,    23,    14,    15,    16,
    17,    18,    19,    20,    24,   nil,   nil,    21,    22,    23,
    14,    15,    16,    17,    18,    19,    20,    24,   nil,   nil,
    21,    22,    23,    14,    15,    16,    17,    18,    19,    20,
    24,   nil,   nil,    21,    22,    23,    14,    15,    16,    17,
    18,    19,    20,    24,   nil,   nil,    21,    22,    23,    14,
    15,    16,    17,    18,    19,    20,    24,   nil,   nil,    21,
    22,    23,    14,    15,    16,    17,    18,    19,    20,    24,
   nil,   nil,    21,    22,    23,    14,    15,    16,    17,    18,
    19,    20,    24,   nil,   nil,    21,    22,    23,    14,    15,
    16,    17,    18,    19,    20,    24,     5,    27,    21,    38,
    39,    14,   nil,    27,    85,    38,    39,    36,    37,    32,
    33,    34,    35,    27,    14,    38,    39,    36,    37,   nil,
    27,     6,    38,    39,    36,    37,    32,    33,    34,    35,
    30,    31,    29,    28,   nil,   nil,   nil,    27,    61,    38,
    39,    36,    37,    32,    33,    34,    35,    30,    31,    29,
    28,    27,   nil,    38,    39,    36,    37,    32,    33,    34,
    35,    30,    31,    29,    28,    27,   nil,    38,    39,    36,
    37,    32,    33,    34,    35,    30,    31,    29,    28,    27,
   nil,    38,    39,    36,    37,    32,    33,    34,    35,    30,
    31,    29,    28,    27,   nil,    38,    39,    36,    37,    32,
    33,    34,    35,    30,    31,    29,    28,    27,   nil,    38,
    39,    36,    37,    32,    33,    34,    35,    30,    31,    29,
    27,   nil,    38,    39,    36,    37,    32,    33,    34,    35,
    30,    31,    27,   nil,    38,    39,    36,    37,    32,    33,
    34,    35,    27,   nil,    38,    39,    36,    37,    27,   nil,
    38,    39,    36,    37,    27,   nil,    38,    39,    36,    37,
    27,   nil,    38,    39 ]

racc_action_check = [
     0,     0,     0,     0,     0,     0,     0,     0,     0,     0,
    66,    23,     0,    82,    82,    82,    82,    82,    82,    82,
    82,    82,    82,    75,    22,    82,    75,     0,     0,     2,
    42,    42,    27,    42,    42,    42,    42,    42,    42,    42,
    82,    82,    42,    41,    41,    78,    41,    41,    41,    41,
    41,    41,    41,    25,     2,    41,    14,    14,    42,    14,
    14,    14,    14,    14,    14,    14,    62,    60,    14,    62,
    78,    41,    45,    65,    65,    65,    65,    65,    65,    65,
    65,    65,    65,    59,    14,    65,    21,    21,    74,    21,
    21,    21,    21,    21,    21,    21,    74,    45,    21,    20,
    65,    65,    20,    39,    39,    48,    39,    39,    39,    39,
    39,    39,    39,    74,    21,    39,    70,    70,    79,    70,
    70,    70,    70,    70,    70,    70,     1,    44,    70,    68,
    68,    39,    68,    68,    68,    68,    68,    68,    68,    43,
   nil,    68,    26,    26,    70,    26,    26,    26,    26,    26,
    26,    26,    44,    44,    26,    72,   nil,    68,    72,    67,
    67,    67,    67,    67,    67,    67,    67,    67,    67,   nil,
    26,    67,    28,    28,    71,    28,    28,    28,    28,    28,
    28,    28,    71,   nil,    28,   nil,    67,    67,   nil,    29,
    29,   nil,    29,    29,    29,    29,    29,    29,    29,    71,
    28,    29,    38,    38,   nil,    38,    38,    38,    38,    38,
    38,    38,   nil,   nil,    38,    31,    31,    29,    31,    31,
    31,    31,    31,    31,    31,   nil,   nil,    31,    32,    32,
    38,    32,    32,    32,    32,    32,    32,    32,   nil,   nil,
    32,    33,    33,    31,    33,    33,    33,    33,    33,    33,
    33,   nil,   nil,    33,    34,    34,    32,    34,    34,    34,
    34,    34,    34,    34,   nil,   nil,    34,    35,    35,    33,
    35,    35,    35,    35,    35,    35,    35,   nil,   nil,    35,
    36,    36,    34,    36,    36,    36,    36,    36,    36,    36,
   nil,   nil,    36,    37,    37,    35,    37,    37,    37,    37,
    37,    37,    37,   nil,   nil,    37,    30,    30,    36,    30,
    30,    30,    30,    30,    30,    30,    84,    58,    30,    58,
    58,    37,   nil,    51,    84,    51,    51,    51,    51,    51,
    51,    51,    51,    56,    30,    56,    56,    56,    56,   nil,
    40,    84,    40,    40,    40,    40,    40,    40,    40,    40,
    40,    40,    40,    40,   nil,   nil,   nil,    76,    40,    76,
    76,    76,    76,    76,    76,    76,    76,    76,    76,    76,
    76,     3,   nil,     3,     3,     3,     3,     3,     3,     3,
     3,     3,     3,     3,     3,    47,   nil,    47,    47,    47,
    47,    47,    47,    47,    47,    47,    47,    47,    47,    64,
   nil,    64,    64,    64,    64,    64,    64,    64,    64,    64,
    64,    64,    64,    63,   nil,    63,    63,    63,    63,    63,
    63,    63,    63,    63,    63,    63,    63,    49,   nil,    49,
    49,    49,    49,    49,    49,    49,    49,    49,    49,    49,
    50,   nil,    50,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    52,   nil,    52,    52,    52,    52,    52,    52,
    52,    52,    55,   nil,    55,    55,    55,    55,    54,   nil,
    54,    54,    54,    54,    53,   nil,    53,    53,    53,    53,
    57,   nil,    57,    57 ]

racc_action_pointer = [
    -3,   126,    24,   357,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,    53,   nil,   nil,   nil,   nil,   nil,
    71,    83,    13,    -1,   nil,    53,   139,    21,   169,   186,
   303,   212,   225,   238,   251,   264,   277,   290,   199,   100,
   326,    40,    27,   125,   122,    67,   nil,   371,    74,   413,
   426,   309,   438,   460,   454,   448,   319,   466,   303,    69,
    53,   nil,    37,   399,   385,    70,    -1,   156,   126,   nil,
   113,   169,   126,   nil,    83,    -6,   343,   nil,    40,   107,
   nil,   nil,    10,   nil,   311,   nil ]

racc_action_default = [
    -1,   -50,    -2,    -3,    -6,    -7,    -8,    -9,   -10,   -11,
   -12,   -13,   -14,   -15,   -50,   -17,   -18,   -19,   -20,   -21,
   -22,   -50,   -50,   -50,   -49,   -50,    -5,   -50,   -50,   -50,
   -50,   -50,   -50,   -50,   -50,   -50,   -50,   -50,   -50,   -50,
   -50,   -26,   -50,   -41,   -50,   -50,    86,    -4,   -24,   -29,
   -30,   -31,   -32,   -33,   -34,   -35,   -36,   -37,   -38,   -39,
   -40,   -16,   -50,   -27,   -42,   -50,   -45,   -50,   -26,   -23,
   -50,   -50,   -50,   -46,   -50,   -50,   -28,   -43,   -50,   -50,
   -48,   -25,   -50,   -47,   -50,   -44 ]

racc_goto_table = [
    26,     2,    40,     1,    62,    72,   nil,   nil,   nil,    43,
   nil,   nil,   nil,   nil,    47,   nil,    49,    50,    51,    52,
    53,    54,    55,    56,    57,    58,    59,    60,   nil,    63,
    64,    75,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,    65,    67,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    63,   nil,    76,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,    71,   nil,    74,    26,
   nil,   nil,    26,   nil,   nil,   nil,    82,   nil,   nil,   nil,
   nil,   nil,    26,    84 ]

racc_goto_check = [
     4,     2,     3,     1,    12,    13,   nil,   nil,   nil,     3,
   nil,   nil,   nil,   nil,     3,   nil,     3,     3,     3,     3,
     3,     3,     3,     3,     3,     3,     3,     3,   nil,     3,
     3,    12,   nil,   nil,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,     4,     4,   nil,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     3,   nil,     3,   nil,
   nil,   nil,   nil,   nil,   nil,   nil,     2,   nil,     2,     4,
   nil,   nil,     4,   nil,   nil,   nil,     4,   nil,   nil,   nil,
   nil,   nil,     4,     2 ]

racc_goto_pointer = [
   nil,     3,     1,   -12,    -2,   nil,   nil,   nil,   nil,   nil,
   nil,   nil,   -37,   -61 ]

racc_goto_default = [
   nil,   nil,   nil,     3,     4,     7,     8,     9,    10,    11,
    12,    13,   nil,   nil ]

racc_reduce_table = [
  0, 0, :racc_error,
  0, 34, :_reduce_1,
  1, 34, :_reduce_2,
  1, 35, :_reduce_3,
  3, 35, :_reduce_4,
  2, 35, :_reduce_5,
  1, 35, :_reduce_6,
  1, 37, :_reduce_none,
  1, 37, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  1, 36, :_reduce_none,
  3, 36, :_reduce_16,
  1, 38, :_reduce_17,
  1, 38, :_reduce_18,
  1, 38, :_reduce_19,
  1, 38, :_reduce_20,
  1, 38, :_reduce_21,
  1, 39, :_reduce_22,
  4, 39, :_reduce_23,
  3, 39, :_reduce_24,
  6, 39, :_reduce_25,
  0, 45, :_reduce_26,
  1, 45, :_reduce_27,
  3, 45, :_reduce_28,
  3, 40, :_reduce_29,
  3, 40, :_reduce_30,
  3, 40, :_reduce_31,
  3, 40, :_reduce_32,
  3, 40, :_reduce_33,
  3, 40, :_reduce_34,
  3, 40, :_reduce_35,
  3, 40, :_reduce_36,
  3, 40, :_reduce_37,
  3, 40, :_reduce_38,
  3, 40, :_reduce_39,
  3, 40, :_reduce_40,
  2, 40, :_reduce_41,
  3, 42, :_reduce_42,
  5, 43, :_reduce_43,
  8, 43, :_reduce_44,
  0, 46, :_reduce_45,
  1, 46, :_reduce_46,
  3, 46, :_reduce_47,
  5, 44, :_reduce_48,
  1, 41, :_reduce_49 ]

racc_reduce_n = 50

racc_shift_n = 86

racc_token_table = {
  false => 0,
  :error => 1,
  :IF => 2,
  :DEF => 3,
  :CLASS => 4,
  :NEWLINE => 5,
  :NUMBER => 6,
  :STRING => 7,
  :TRUE => 8,
  :FALSE => 9,
  :NIL => 10,
  :IDENTIFIER => 11,
  :CONSTANT => 12,
  :END => 13,
  "." => 14,
  "!" => 15,
  "*" => 16,
  "/" => 17,
  "+" => 18,
  "-" => 19,
  ">" => 20,
  ">=" => 21,
  "<" => 22,
  "<=" => 23,
  "==" => 24,
  "!=" => 25,
  "&&" => 26,
  "||" => 27,
  "=" => 28,
  "," => 29,
  ";" => 30,
  "(" => 31,
  ")" => 32 }

racc_nt_base = 33

racc_use_result_var = true

Racc_arg = [
  racc_action_table,
  racc_action_check,
  racc_action_default,
  racc_action_pointer,
  racc_goto_table,
  racc_goto_check,
  racc_goto_default,
  racc_goto_pointer,
  racc_nt_base,
  racc_reduce_table,
  racc_token_table,
  racc_shift_n,
  racc_reduce_n,
  racc_use_result_var ]

Racc_token_to_s_table = [
  "$end",
  "error",
  "IF",
  "DEF",
  "CLASS",
  "NEWLINE",
  "NUMBER",
  "STRING",
  "TRUE",
  "FALSE",
  "NIL",
  "IDENTIFIER",
  "CONSTANT",
  "END",
  "\".\"",
  "\"!\"",
  "\"*\"",
  "\"/\"",
  "\"+\"",
  "\"-\"",
  "\">\"",
  "\">=\"",
  "\"<\"",
  "\"<=\"",
  "\"==\"",
  "\"!=\"",
  "\"&&\"",
  "\"||\"",
  "\"=\"",
  "\",\"",
  "\";\"",
  "\"(\"",
  "\")\"",
  "$start",
  "Root",
  "Expressions",
  "Expression",
  "Terminator",
  "Literal",
  "Call",
  "Operator",
  "Constant",
  "Assign",
  "Def",
  "Class",
  "ArgList",
  "ParamList" ]

Racc_debug_parser = false

##### State transition tables end #####

# reduce 0 omitted

module_eval(<<'.,.,', 'grammar.y', 46)
  def _reduce_1(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 47)
  def _reduce_2(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 52)
  def _reduce_3(val, _values, result)
     result = Nodes.new(val) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 53)
  def _reduce_4(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 55)
  def _reduce_5(val, _values, result)
     result = val[0] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 56)
  def _reduce_6(val, _values, result)
     result = Nodes.new([]) 
    result
  end
.,.,

# reduce 7 omitted

# reduce 8 omitted

# reduce 9 omitted

# reduce 10 omitted

# reduce 11 omitted

# reduce 12 omitted

# reduce 13 omitted

# reduce 14 omitted

# reduce 15 omitted

module_eval(<<'.,.,', 'grammar.y', 74)
  def _reduce_16(val, _values, result)
     result = val[1] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 79)
  def _reduce_17(val, _values, result)
     result = NumberNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 80)
  def _reduce_18(val, _values, result)
     result = StringNode.new(val[0]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 81)
  def _reduce_19(val, _values, result)
     result = TrueNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 82)
  def _reduce_20(val, _values, result)
     result = FalseNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 83)
  def _reduce_21(val, _values, result)
     result = NilNode.new 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 88)
  def _reduce_22(val, _values, result)
     result = CallNode.new(nil, val[0], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 89)
  def _reduce_23(val, _values, result)
     result = CallNode.new(nil, val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 90)
  def _reduce_24(val, _values, result)
     result = CallNode.new(val[0], val[2], []) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 92)
  def _reduce_25(val, _values, result)
     result = CallNode.new(val[0], val[2], val[4]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 96)
  def _reduce_26(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 97)
  def _reduce_27(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 98)
  def _reduce_28(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 103)
  def _reduce_29(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 104)
  def _reduce_30(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 105)
  def _reduce_31(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 106)
  def _reduce_32(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 107)
  def _reduce_33(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 108)
  def _reduce_34(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 109)
  def _reduce_35(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 110)
  def _reduce_36(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 111)
  def _reduce_37(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 112)
  def _reduce_38(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 113)
  def _reduce_39(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 114)
  def _reduce_40(val, _values, result)
     result = CallNode.new(val[0], val[1], [val[2]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 116)
  def _reduce_41(val, _values, result)
     result = CallNode.new(nil, val[0], [val[1]]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 121)
  def _reduce_42(val, _values, result)
     result = AssignNode.new(val[0], val[2]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 128)
  def _reduce_43(val, _values, result)
     result = DefNode.new(val[1], [], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 131)
  def _reduce_44(val, _values, result)
     result = DefNode.new(val[1], val[3], val[6]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 135)
  def _reduce_45(val, _values, result)
     result = [] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 136)
  def _reduce_46(val, _values, result)
     result = val 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 137)
  def _reduce_47(val, _values, result)
     result = val[0] << val[2] 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 144)
  def _reduce_48(val, _values, result)
     result = ClassNode.new(val[1], val[3]) 
    result
  end
.,.,

module_eval(<<'.,.,', 'grammar.y', 149)
  def _reduce_49(val, _values, result)
     result = ConstantNode.new(val[0]) 
    result
  end
.,.,

def _reduce_none(val, _values, result)
  val[0]
end

end   # class Parser
